-- =============================================================================
-- schema.sql — executed via JDBC on startup before R2DBC connections open
-- Works for both H2 (default profile) and PostgreSQL (postgres profile)
-- =============================================================================

CREATE TABLE IF NOT EXISTS tasks (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          VARCHAR(64)     NOT NULL,
    sequence      INTEGER         NOT NULL,
    type          INTEGER         NOT NULL,
    description   VARCHAR(255)    NOT NULL,
    state         VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    processed_by  VARCHAR(255),
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at    TIMESTAMP,
    completed_at  TIMESTAMP,
    error_message VARCHAR(1000),
    retry_count   INTEGER         NOT NULL DEFAULT 0,
    CONSTRAINT uk_task_uuid_sequence_type UNIQUE (uuid, sequence, type)
);

CREATE INDEX IF NOT EXISTS idx_tasks_state    ON tasks (state, created_at);
CREATE INDEX IF NOT EXISTS idx_tasks_uuid     ON tasks (uuid);

-- ShedLock table — managed by R2dbcLockProvider
CREATE TABLE IF NOT EXISTS shedlock (
    name        VARCHAR(64)  NOT NULL,
    lock_until  TIMESTAMP    NOT NULL,
    locked_at   TIMESTAMP    NOT NULL,
    locked_by   VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);
